### ISSUE TITLE
Strange warning shown after updating today 

### ISSUE THREAD

**Issue by cleanerspam** [Vanilla-OS/desktop-image#189]
### Issue Description

Today from blac-box i updated system manually using abroot upgrade and after that rebooted , On login screen I entered password and system rejected it as wrong password then after some time with same password the spiining animation kept on going and system allowed login , where when i tried to open black box it showed following warning 

![Screenshot from 2024-07-31 09-19-45](https://github.com/user-attachments/assets/ef8f5a55-7523-4c79-9d06-4cba9fc4fad1)

After which I rebooted and it fixed error , How can i check what caused that error and if system rolled-back update , abroot upgrade shows no new update found

### Steps to Reproduce

run abroot upgrade today 
reboot 
if login takes too much time 
then you may also face this issue 

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

**Comment by taukakao** [comment]
Something failed while logging in. The reason is probably somewhere deep in the logs when you run "host-shell journalctl"

The container was probably halfway started which is why it showed this error. 

I would recommend just waiting if this happens again and then using a tty to read the error right after.
