### ISSUE TITLE
Slow first-install shell

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/desktop-image#22]
The vanilla first setup takes unusually long to load in the restricted shell. 

This seems very similar to the problem in the installer shell for the live-iso.

**Comment by taukakao** [comment]
@matbme 
I think you worked on the issue in the live-iso. 
I would appreciate it a lot of you could have a look.

I can also fix this is you want, in which case I would still appreciate some hints.

**Comment by matbme** [comment]
[This commit](https://github.com/Vanilla-OS/live-iso/commit/94cf5fa0f525fd163536dd59990de874681e6c68) is what fixed the slow startup in the live ISO, but I'm hesitant to add the same file to the desktop image since the issue seems to fix itself after a reboot. Maybe it's something related to the restricted shell?

The issue happens because `xdg-desktop-portal-gnome` by default depends on the `graphical-session.target` Systemd target to start, but for some reason this target doesn't get activated when we boot into the restricted shell.

If there's no proper solution, ideally we'd include the modified unit file in the image and then remove it once first-setup has completed

**Comment by taukakao** [comment]
Thank you, but I think removing it later is not a good option here, since first-setup will be run for new users as well.

Interestingly enough, even if graphical.target is active, the dependency fails for some reason.

**Comment by taukakao** [comment]
Ok the custom mode in `/usr/share/gnome-shell/modes/firstsetup.json` is fine, just the custom session is causing the problems here.

**Comment by taukakao** [comment]
Ok, I think this is because gnome-session.target isn't reached in the custom session.

**Comment by matbme** [comment]
Closed in first-setup by the following commits:

- https://github.com/Vanilla-OS/first-setup/commit/89ebdda5dd1cc32930bdbf7a71ef24ec8e43ffab
- https://github.com/Vanilla-OS/first-setup/commit/901209e02e83a9739aaf10535ba7d2917bc87629
